config/routes.rb
Rails.application.routes.draw do

  resources :caves do
    resources :reviews, except: [:show, :index]
    resources :images, except: [:show, :index]
    resources :sessions
      resources :sessions, only: [:new, :create]
  end

  resources :subscribers
  resources :payments  #, only: [:new, :create]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/pricing'
  get 'mycafes' => "caves#mycafes"
  get 'customers' => "sessions#customers"
  get 'mysessions' => "sessions#mysessions" 

  resources :owners

  resources :workers

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'caves#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    delete "signup" => "users/sessions#destroy"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    patch    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  ActiveAdmin.routes(self)

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)
    @owner.user = current_user

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:user_id, :address, :state, :city, :zipcode, :description, :rating, :image)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for @owner, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zipcode, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :zipcode, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :rating, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :image, :class => 'file-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  owners_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/owners/edit.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Owner %></h1>
</div>
<%= render :partial => 'form' %>

app/views/owners/index.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1>Owners</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.id %></td>
        <td><%= owner.address %></td>
        <td><%= owner.state %></td>
        <td><%= owner.city %></td>
        <td><%= owner.zipcode %></td>
        <td><%= owner.description %></td>
        <td><%= owner.rating %></td>
        <td><%=l owner.created_at, format: :long %></td>
        <td>
          <%= link_to owner_path(owner), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to owner_path(owner), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_owner_path,
            :class => 'btn btn-primary' %>

app/views/owners/new.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Owner %></h1>
</div>
<%= render :partial => 'form' %>

app/views/owners/show.html.erb
<%- model_class = Owner -%>
<div class="page-header">
  <h1><%=t '.title', :default => Owner %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address) %></dt>
      <dd><pre class="prettyprint"><%= @owner.address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state) %></dt>
      <dd><pre class="prettyprint"><%= @owner.state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city) %></dt>
      <dd><pre class="prettyprint"><%= @owner.city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:zipcode) %></dt>
      <dd><pre class="prettyprint"><%= @owner.zipcode %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @owner.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rating) %></dt>
      <dd><pre class="prettyprint"><%= @owner.rating %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              owners_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_owner_path(@owner), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              owner_path(@owner),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>