config/routes.rb
Rails.application.routes.draw do

  resources :caves do
    resources :reviews, except: [:show, :index]
    resources :images, except: [:show, :index]
    resources :sessions
      resources :sessions, only: [:new, :create]
  end

  resources :subscribers
  resources :payments  #, only: [:new, :create]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/pricing'
  get 'mycafes' => "caves#mycafes"
  get 'customers' => "sessions#customers"
  get 'mysessions' => "sessions#mysessions" 

  resources :owners

  resources :workers

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'caves#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    delete "signup" => "users/sessions#destroy"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    patch    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  ActiveAdmin.routes(self)

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :user
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)
    @worker.user = current_user

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:user_id, :count)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for @worker, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :count, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  workers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/workers/edit.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Worker %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workers/index.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => Worker %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:count) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.id %></td>
        <td><%= worker.count %></td>
        <td><%=l worker.created_at, format: :long %></td>
        <td>
          <%= link_to worker_path(worker), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to worker_path(worker), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_worker_path,
            :class => 'btn btn-primary' %>

app/views/workers/new.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Worker %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workers/show.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => Worker %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:count) %></dt>
      <dd><pre class="prettyprint"><%= @worker.count %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              workers_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_worker_path(@worker), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              worker_path(@worker),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>