config/routes.rb
Rails.application.routes.draw do

  resources :caves do
    resources :reviews, except: [:show, :index]
    resources :images, except: [:show, :index]
    resources :sessions
      resources :sessions, only: [:new, :create]
  end

  resources :subscribers
  resources :payments  #, only: [:new, :create]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/pricing'
  get 'mycafes' => "caves#mycafes"
  get 'customers' => "sessions#customers"
  get 'mysessions' => "sessions#mysessions" 

  resources :owners

  resources :workers

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'caves#index'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    delete "signup" => "users/sessions#destroy"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    patch    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  ActiveAdmin.routes(self)

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  before_filter :authenticate_user!


  def new

  end

  def update

      token = params[:stripeToken]

      customer = Stripe::Customer.create(
        card: token,
        plan: 1020,
        email: current_user.email
      )
      current_user.subscribed = true
      current_user.credit = 0.00
      current_user.stripeid = customer.id
      current_user.save

      redirect_to caves_path

  end




end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="19900"></script><span> $199 per month, cancel at any time.</span>
<% end %>

app/views/subscribers/new.html.erb
<br>

<div class="container">
      <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
          <div class="panel-body">
              <h2>CoWorker Classic</h2>
              <br>
              <h4>This is the final step to grant you access.</h4>
              <h4>Lets get to work!</h4>
              <br>
              <br>
              <h3>$199</h3>
              <br>
              <%= render 'form' %>
          </div>
      </div>
</div>